@startuml
skinparam monochrome true
skinparam shadowing false
skinparam linetype ortho
top to bottom direction

actor Client as C
actor Agent as A


usecase "Регистрация" as UC_Reg
usecase "Вход" as UC_Login
usecase "Просмотр туров" as UC_View
usecase "Выбор тура" as UC_Select
usecase "Оплата тура" as UC_Pay
usecase "Отмена заказа" as UC_Cancel

usecase "Добавить тур" as UC_Add
usecase "Редактировать тур" as UC_Edit
usecase "Отметить как горящий" as UC_Hot
usecase "Настроить скидки" as UC_Discount

UC_Select --> UC_Pay : <<include>>
UC_Edit --> UC_View : <<include>>


C --> UC_Reg
C --> UC_Login
C --> UC_View
C --> UC_Select
C --> UC_Cancel

A --> UC_Login
A --> UC_Add
A --> UC_Edit
A --> UC_Hot
A --> UC_Discount



@enduml
