@startuml
skinparam monochrome true
skinparam linetype ortho
top to bottom direction

component Browser_

rectangle "Турагентство" {
  component UI_
  component Auth_
  component TourService_
  component OrderService_
  component DiscountService_
  component PaymentAdapter_
  component DB_
}

Browser_ --> UI_
UI_ --> Auth_
UI_ --> TourService_
UI_ --> OrderService_
UI_ --> DiscountService_

TourService_ --> DB_
OrderService_ --> DB_
Auth_ --> DB_

OrderService_ --> PaymentAdapter_

@enduml
